{{ range $name, $info := .Values.users }}
{{- if not $info.disabled }}
{{- $certName := printf "%s-postgres-%s-user" $.Values.clusterName $name -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $certName }}
spec:
  secretName: {{ $certName }}
  usages:
    - client auth
  commonName: {{ $info.username }}
  duration: {{ $info.duration | default "1h" }}
{{- if $info.renewBefore }}
  renewBefore: {{ $info.renewBefore }}
{{- end }}
{{- if not $info.disableReloading }}
  secretTemplate: {{ include "cnpg-labels" $ | nindent 4 }}
{{- end }}
  issuerRef: {{ include "ca-issuer-ref" $ | nindent 4 }}
---
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: {{ $.Values.clusterName }}-postgres-auth-ca-{{ $name }}-user
spec:
  selector:
    issuerRef: {{ include "ca-issuer-ref" $ | nindent 6 }}
    namespace:
      matchNames:
        - {{ $.Release.Namespace }}
  allowed:
    commonName:
      required: true
      value: {{ $info.username }}
    usages:
      - client auth
  constraints:
    maxDuration: {{ $info.duration | default "1h" }}
{{- end }}
{{ end }}
