---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: openarc-asr
specs:
  - description: openarc
    endpointSelector:
      matchLabels:
        app.kubernetes.io/name: openarc-asr
        app.kubernetes.io/controller: openarc
        app.kubernetes.io/instance: openarc-asr
    ingress:
      - fromEntities:
          - host
        toPorts:
          - ports:
              - port: "8000"
                protocol: TCP
      - fromEndpoints:
          - matchLabels:
              app.kubernetes.io/name: bazarr
              app.kubernetes.io/controller: bazarr
              app.kubernetes.io/instance: bazarr
        toPorts:
          - ports:
              - port: "8000"
                protocol: TCP
  - description: setup
    endpointSelector:
      matchLabels:
        app.kubernetes.io/name: openarc-asr
        app.kubernetes.io/controller: setup
        app.kubernetes.io/instance: openarc-asr
    egress:
      - toEndpoints:
          - matchLabels:
              io.kubernetes.pod.namespace: networking
              endpoints.netpols.home.arpa/cluster-dns: "true"
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
            rules:
              dns: &fqdns
                - matchPattern: huggingface.co
                - matchPattern: "**.huggingface.co"
                - matchPattern: "**.hf.co"
      - toFQDNs: *fqdns
        toPorts:
          - ports:
              - port: "443"
                protocol: TCP
