---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: minecraft-router
  labels: &labels
    app.kubernetes.io/name: minecraft-router
    app.kubernetes.io/instance: minecraft-router
    app.kubernetes.io/component: minecraft-router
spec:
  minAvailable: 1
  selector:
    matchLabels: *labels
