---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: system-upgrade-controller
  labels: &labels
    app.kubernetes.io/name: system-upgrade-controller
    app.kubernetes.io/instance: system-upgrade-controller
    app.kubernetes.io/component: system-upgrade-controller
spec:
  minAvailable: 1
  selector:
    matchLabels: *labels
