---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 1h
  chart:
    spec:
      chart: node-feature-discovery
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: node-feature-discovery-charts
      version: 0.17.2
  values:
    featureGates:
      NodeFeatureGroupAPI: true
    prometheus:
      enable: true
    master:
      replicaCount: 2
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 64Mi
    worker:
      resources:
        requests:
          cpu: 5m
          memory: 64Mi
        limits:
          memory: 64Mi
    gc:
      replicaCount: 1
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 64Mi
