---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: flux-system
  name: &app_name renovate-operator-backend
spec:
  targetNamespace: development
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app_name
  interval: 5m
  path: /cluster/gitops/development/renovate-operator/backend
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-mk3
  wait: true
  dependsOn:
    - name: rook-ceph-cluster
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: flux-system
  name: &app_name renovate-operator-app
spec:
  targetNamespace: development
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app_name
  interval: 5m
  path: /cluster/gitops/development/renovate-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-mk3
  wait: true
  dependsOn:
    - name: prometheus-crds
    - name: gateway-crds
    - name: grafana-crds
    - name: renovate-operator-backend
    - name: fluent-crds
---
# RenovateJob CRs: the CRDs ship with the operator chart.
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: flux-system
  name: &app_name renovate-operator-jobs
spec:
  targetNamespace: development
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app_name
  interval: 5m
  path: /cluster/gitops/development/renovate-operator/jobs
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-mk3
  wait: true
  dependsOn:
    - name: renovate-operator-app
