{
 "title": "Certificate manager",
 "tags": [ "cert-manager" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(certmanager_certificate_ready_status,exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Certificates issued in time range",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  changes(\r\n    avg(\r\n      certmanager_certificate_renewal_timestamp_seconds[15m]\r\n    ) without(instance,pod)\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready certificates",
   "type": "stat",
   "description": "The number of certificates in \"Ready\" state",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(certmanager_certificate_ready_status{condition=\"True\", exported_namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not ready certificates",
   "type": "stat",
   "description": "The number of certificates _not_ in \"Ready\" state",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(certmanager_certificate_ready_status{condition!=\"True\", exported_namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certificates past renewal threshold",
   "type": "stat",
   "description": "The number of certificates that should have renewed already, but have not.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(certmanager_certificate_renewal_timestamp_seconds{exported_namespace=~\"$namespace\"} < time() - 120) or 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Renewals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Renewal lifecycle (all)",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\"} - time())\r\n  / on(name,exported_namespace)\r\n(\r\n  certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\"}\r\n    - on(name,exported_namespace)\r\n  label_replace(\r\n    kube_customresource_certificate_issuance_timestamp_seconds{namespace=~\"$namespace\"},\r\n    \"exported_namespace\",\r\n    \"$1\",\r\n    \"namespace\",\r\n    \"(.+)\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\"} - time()) by(exported_namespace,name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Renewal lifecycle (minimum per namespace)",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "min(\r\n  (\r\n    certmanager_certificate_expiration_timestamp_seconds{\r\n      exported_namespace=~\"$namespace\"\r\n    }\r\n      -\r\n    time()\r\n  )\r\n    / on(name,exported_namespace)\r\n  (\r\n    certmanager_certificate_expiration_timestamp_seconds{\r\n      exported_namespace=~\"$namespace\"\r\n    }\r\n      - on(name,exported_namespace)\r\n    label_replace(\r\n      kube_customresource_certificate_issuance_timestamp_seconds{\r\n        namespace=~\"$namespace\"\r\n      },\r\n      \"exported_namespace\",\r\n      \"$1\",\r\n      \"namespace\",\r\n      \"(.+)\"\r\n    )\r\n  )\r\n) by(exported_namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "min (certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\"} - time()) by(exported_namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining valid lifetime (all)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\"} - time())\r\n  / on(name,exported_namespace)\r\n(\r\n  certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\"}\r\n    - on(name,exported_namespace)\r\n  label_replace(\r\n    kube_customresource_certificate_issuance_timestamp_seconds{namespace=~\"$namespace\"},\r\n    \"exported_namespace\",\r\n    \"$1\",\r\n    \"namespace\",\r\n    \"(.+)\"\r\n  )\r\n)",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Remaining valid lifetime (minimum per namespace)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min(\r\n  (\r\n    certmanager_certificate_expiration_timestamp_seconds{\r\n      exported_namespace=~\"$namespace\"\r\n    }\r\n      -\r\n    time()\r\n  )\r\n    / on(name,exported_namespace)\r\n  (\r\n    certmanager_certificate_expiration_timestamp_seconds{\r\n      exported_namespace=~\"$namespace\"\r\n    }\r\n      - on(name,exported_namespace)\r\n    label_replace(\r\n      kube_customresource_certificate_issuance_timestamp_seconds{\r\n        namespace=~\"$namespace\"\r\n      },\r\n      \"exported_namespace\",\r\n      \"$1\",\r\n      \"namespace\",\r\n      \"(.+)\"\r\n    )\r\n  )\r\n) by(exported_namespace)",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Renewal events (per issuer)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  sum(\r\n    label_replace(\r\n      label_join(\r\n        label_join(\r\n          sum(\r\n            changes(\r\n              avg(\r\n                certmanager_certificate_renewal_timestamp_seconds{exported_namespace=~\"$namespace\"}[15m]\r\n              ) without(instance,pod)\r\n            )\r\n          ) by(issuer_kind,issuer_name,exported_namespace),\r\n          \"issuer_identifier\",\r\n          \": \",\r\n          \"issuer_kind\",\r\n          \"exported_namespace\"\r\n        ),\r\n        \"issuer_identifier\",\r\n        \"/\",\r\n        \"issuer_identifier\",\r\n        \"issuer_name\"\r\n      ),\r\n      \"issuer_identifier\",\r\n      \"ClusterIssuer: $1\",\r\n      \"issuer_identifier\",\r\n      \"ClusterIssuer: .*?/(.+)\"\r\n    )\r\n  ) without(exported_namespace),\r\n  \"exported_namespace\",\r\n  \"$1\",\r\n  \"issuer_identifier\",\r\n  \"Issuer: (.+?)/.*\"\r\n)",
     "legendFormat": "{{issuer_identifier}}"
    }
   ]
  }
 ]
}