apiVersion: v1
kind: Secret
metadata:
  name: coder-pull-credentials
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:L3TD4ljkCbgymeNGad6T2+jcy2Bbe0vpATYpmsmlsgVhVSNCIVr03pzXhuO0UgrhzowqnLSoPS8eaLQGhHtbeQ6eRY12PUCpDxznmgIxVwETEgWWpST54iZIFnABcYC89uetb29PWBAc2/zFwjV5SKyhM1u1TU7D7lPa6tLPdMmths1RkJlYdq/+Uk3I9kaLURYXpdOYaHHy0ZcNhTnCJzNP,iv:p6W3WxikEcIPqjMgVkSrNyPgJafPDp2024ufpc0Joew=,tag:aQQ5EAbrUrrPw4bAUJhb/w==,type:str]
  accessKeyId: ENC[AES256_GCM,data:z0KOH8XbyWHe3gjG5kDU3IAlezaATgLwdKVABlKdVIH1,iv:pJqqpNUiVnsLXX/gj7wmlBIYi0Euq9DPH5t5cfvS4IU=,tag:sQlQiYOBVvZ94KfyU7YmRw==,type:str]
  secretKey: ENC[AES256_GCM,data:ecEUMfgjHJZF8kV8CSl6m2bItsf5xZzgYZczVlNunug=,iv:U0SxYQ1IamU/8TTRjnGPptdbHWQS8jydMlWlUMChfxM=,tag:HGeZS3yhyCJLiVcu6Vz67A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ul782d9yhczht238qh9unx5swcjjdy8va7gdhcmgd3duvt5dxfgsa35mjh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RFpSZnZSbHV2L0pEemJF
        eWdSTXJ5WlEybFhwRUM0UTdUTTNZK1pYUWlvCm9tMEdXR1Q3eTBEWjBRb0lkbjQ3
        R1dpM0tGVHBlcTdnOXp1L0hzSWdJN2MKLS0tIDJLbzRSZ3FJclhOTUpEYk5GMTR2
        aEs3aUFUTGVvdkJsbkNiaWswSmt2dmcKAvvqpW/DcBSuuY4BbhZeyyYaeVcah5XP
        tTkuNOhpMneaslnDnIlrzH+IXWpPnqd7ezpNdgFI60aP9XsSOT5T1g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1cy90dzmcmw09wluc6ghvfltf8x2kxcd2pc0uxk6w55m62uwntunsc89jmk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaUk2OXRSekx6UXRHempw
        ZzQ5QlpVTmR4L3ArRmpEcjlCVkZhVDVaN1dzCkozTEt1WVQzS1ZHUWJRd2t3TDk0
        SlVnK2tmamRSaFdpNmRZb3ROSXJtK3MKLS0tIGQzcUpuRm03NGJveW9KRGZXd2s5
        M2U2Y3JkRmpsNFc3ejBMZEpINXdIQUEK19No7oZ1R6dXXTcTtRnIBPWCHa3i4A3T
        sCx4qhIRaL4VdsRj35JE3rIIGgK/Ny/CZYkFARD2MQfRW+k9AUfyig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-01T06:38:31Z"
  mac: ENC[AES256_GCM,data:E1iIz1tMiR4d+vOKJ8GQYkRDOv57z4SH8lKCIOGSGZMz65/r7nNTFfB/7qBlp4A4VLmG65lSpxYma5WkbDJOBOAFc4zc/hvVCmMrKgY6/Eu3IOVpp1nJjx5xzM0AcbOMIT+1RG5vBlyrR1vdE/hrLi8Bl4KWIecyHES/TDrzc/w=,iv:RDRS9DGOr23tpIcY6Ppt9CjWZ/yLbUZZ5BO/AcajI4k=,tag:aZPQaikqyTnskc/u7gbhgw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.0
