---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./exporters/ks.yaml
  - ./fluent/ks.yaml
  # Disabled due to this bug that the stupid stale bot closed: https://github.com/FairwindsOps/goldilocks/issues/749
  # - ./goldilocks/ks.yaml
  - ./grafana/ks.yaml
  - ./issuers/ks.yaml
  - ./prometheus/ks.yaml
  - ./victoria-metrics/ks.yaml
