#!/usr/bin/env bash
# Regenerates copy-teleport-crs-to-security-policy.yaml.
#
# The Teleport operator only watches resources in its own namespace
# (security), so this policy mirrors every resources.teleport.dev CR from
# any other namespace into security where the operator can reconcile it.
# This workaround can be removed once
# https://github.com/gravitational/teleport/pull/66134 ships.
#
# Why ClusterPolicy v1 instead of GeneratingPolicy v2: the v2 sync path
# has two regressions in Kyverno 1.18 that make multi-kind mirroring
# unreliable:
#   1. (policy-name, target-namespace, target-name) tracking ignores Kind,
#      so resources sharing a name across kinds collapse into one mirror.
#      https://github.com/kyverno/kyverno/issues/15329
#   2. The dynamic_watcher update path emits resourceVersion=0x0 and the
#      API rejects it, leaving mirrors deleted between recreates.
#      https://github.com/kyverno/kyverno/issues/15727
#      https://github.com/kyverno/kyverno/issues/15717
# Both are targeted at milestone 1.19.0. Until then, ClusterPolicy v1's
# generate+clone path is stable: media-processor's mirrors have been live
# under it for hours without flapping. The v1 trade-off is that match
# kinds must be enumerated explicitly (no resources: ["*"]), which this
# script does by reading the live CRD set.
#
# Requires kubectl + jq and a kubeconfig pointing at the cluster whose
# Teleport CRDs are authoritative. Storage version is used per CRD —
# ClusterPolicy v1's match.kinds takes apiGroup/version/Kind tuples and
# only one per CRD is needed.

set -euo pipefail

OUTPUT="$(dirname "$0")/copy-teleport-crs-to-security-policy.yaml"

mapfile -t KINDS < <(
  kubectl get crd -o json \
    | jq -r '.items[]
        | select(.spec.group == "resources.teleport.dev")
        | .spec as $s
        | $s.versions[] | select(.storage == true)
        | "\($s.group)/\(.name)/\($s.names.kind)"' \
    | sort
)

if [[ "${#KINDS[@]}" -eq 0 ]]; then
  echo "error: no resources.teleport.dev CRDs found — is kubectl pointing at the right cluster?" >&2
  exit 1
fi

{
  printf '# DO NOT EDIT — generated by gen-policies.sh in this directory.\n'
  printf '# Re-run the script to refresh the kinds list against the cluster.\n'
  cat <<'EOF'
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kyverno.io/clusterpolicy_v1.json
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: copy-teleport-crs-to-security-namespace
spec:
  # Process pre-existing CRs on policy install/update so they are mirrored
  # without requiring a re-apply of every source.
  generateExisting: true
  rules:
    - name: copy-teleport-cr-to-security
      match:
        any:
          - resources:
              kinds:
EOF
  for kind in "${KINDS[@]}"; do
    printf '                - %s\n' "$kind"
  done
  cat <<'EOF'
      preconditions:
        all:
          - key: "{{ request.namespace }}"
            operator: NotEquals
            value: security
      generate:
        # apiVersion/kind/name templated from the trigger so a single rule
        # covers every kind in the match list. Cross-namespace name
        # collisions are rejected by Kyverno (loud failure) — service-scoped
        # source names should make this rare in practice.
        apiVersion: "{{ request.object.apiVersion }}"
        kind: "{{ request.object.kind }}"
        name: "{{ request.object.metadata.name }}"
        namespace: security
        synchronize: true
        clone:
          namespace: "{{ request.namespace }}"
          name: "{{ request.object.metadata.name }}"
EOF
} > "$OUTPUT"

printf 'Wrote ClusterPolicy with %d kinds to %s\n' "${#KINDS[@]}" "$OUTPUT"
