#!/usr/bin/env bash
# Regenerates copy-teleport-crs-to-security-policy.yaml.
#
# The Teleport operator only watches resources in its own namespace
# (security), so this set of GeneratingPolicies mirrors every
# resources.teleport.dev CR from any other namespace into security where
# the operator can reconcile it. This workaround can be removed once
# https://github.com/gravitational/teleport/pull/66134 ships.
#
# Why one policy per CRD kind (instead of a single policy with
# resources: ["*"]): Kyverno's GeneratingPolicy v2 `synchronize: true`
# cleanup tracks generated resources by
# (policy-name, target-namespace, target-name) and does NOT include the
# resource kind in that key. With a single policy, multiple Teleport CRs
# that share a name across kinds (e.g. TeleportBotV1 / TeleportProvisionToken
# / TeleportWorkloadIdentityV1 all named `media-processor`) collapse into
# a single mirror slot — each new source update wipes the others.
# Splitting per kind gives each kind its own tracking bucket so the
# mirrors can coexist.
#
# Tracked upstream against milestone 1.19.0:
#   https://github.com/kyverno/kyverno/issues/15329
#   https://github.com/kyverno/kyverno/issues/15727
#   https://github.com/kyverno/kyverno/issues/15717
# Once those land, this can collapse back to a single policy with
# resources: ["*"].
#
# Requires kubectl + jq and a kubeconfig pointing at the cluster whose
# Teleport CRDs are authoritative. The script reads the live CRD set so
# adding/removing CRDs only requires a re-run.

set -euo pipefail

OUTPUT="$(dirname "$0")/copy-teleport-crs-to-security-policy.yaml"

mapfile -t KINDS < <(
  kubectl get crd -o json \
    | jq -r '.items[]
        | select(.spec.group == "resources.teleport.dev")
        | .spec.names.plural' \
    | sort
)

if [[ "${#KINDS[@]}" -eq 0 ]]; then
  echo "error: no resources.teleport.dev CRDs found — is kubectl pointing at the right cluster?" >&2
  exit 1
fi

{
  printf '# DO NOT EDIT — generated by gen-policies.sh in this directory.\n'
  printf '# Edit the KINDS list there and re-run the script to update.\n'
  for kind in "${KINDS[@]}"; do
    cat <<EOF
---
# yaml-language-server: \$schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/policies.kyverno.io/generatingpolicy_v1.json
apiVersion: policies.kyverno.io/v1
kind: GeneratingPolicy
metadata:
  name: copy-${kind}-to-security
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: [resources.teleport.dev]
        apiVersions: ["*"]
        operations: ["*"]
        resources: [${kind}]
  matchConditions:
    - name: only-create-or-update
      expression: request.operation in ['CREATE', 'UPDATE']
    - name: not-already-in-security
      expression: object.metadata.namespace != 'security'
  evaluation:
    synchronize:
      enabled: true
    generateExisting:
      enabled: true
  generate:
    - expression: generator.Apply('security', [object])
EOF
  done
} > "$OUTPUT"

printf 'Wrote %d policies to %s\n' "$(grep -c '^---' "$OUTPUT")" "$OUTPUT"
