---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./issuers/ks.yaml
  - ./bazarr/ks.yaml
  - ./jellyfin/ks.yaml
  - ./media-processor/ks.yaml
  - ./media-temporal-keda-auth/ks.yaml
  - ./openarc/ks.yaml
  - ./radarr/ks.yaml
  - ./seerr/ks.yaml
  - ./sonarr/ks.yaml
