---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api-server
  annotations:
    io.cilium/lb-ipam-ips: 10.34.254.1
spec:
  type: LoadBalancer
  ports:
    - name: https-443
      port: 443
      targetPort: 6443
    - name: https-6443
      port: 6443
      targetPort: 6443
