---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: openid-configuration-proxy-envoy-config
    files:
      - envoy.yaml=./envoy.yaml
    options:
      labels:
        kyverno.home.arpa/reload: "true"
      disableNameSuffixHash: true
