---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: flux-system
  name: &app_name workload-reloader-policy
spec:
  targetNamespace: kyverno
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app_name
  interval: 5m
  path: /cluster/gitops/kyverno/policies/workload-reloader
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-mk3
  wait: true
  dependsOn:
    - name: kyverno-app
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: flux-system
  name: &app_name certificate-revision-limiter-policy
spec:
  targetNamespace: kyverno
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app_name
  interval: 5m
  path: /cluster/gitops/kyverno/policies/certificate-revision-limiter
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-mk3
  wait: true
  dependsOn:
    - name: kyverno-app
    - name: cert-manager
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: flux-system
  name: &app_name teleport-cr-mirror-policy
spec:
  targetNamespace: kyverno
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app_name
  interval: 5m
  path: /cluster/gitops/kyverno/policies/teleport-cr-mirror
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-mk3
  wait: true
  dependsOn:
    - name: kyverno-app
    - name: teleport-crds
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: flux-system
  name: &app_name workload-revision-history-limiter-policy
spec:
  targetNamespace: kyverno
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app_name
  interval: 5m
  path: /cluster/gitops/kyverno/policies/workload-revision-history-limiter
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-mk3
  wait: true
  dependsOn:
    - name: kyverno-app
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: flux-system
  name: &app_name fluentbit-filter-scope-policy
spec:
  targetNamespace: kyverno
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app_name
  interval: 5m
  path: /cluster/gitops/kyverno/policies/fluentbit-filter-scope
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-mk3
  wait: true
  dependsOn:
    - name: kyverno-app
    - name: fluent-crds
