---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/resources.teleport.dev/teleportprovisiontoken_v2.json
apiVersion: resources.teleport.dev/v2
kind: TeleportProvisionToken
metadata:
  name: media-processor
spec:
  roles:
    - Bot
  bot_name: media-processor
  join_method: kubernetes
  kubernetes:
    type: in_cluster
    allow:
      - service_account: media:media-processor
