apiVersion: v1
kind: Secret
metadata:
    name: project-zomboid-credentials
type: Opaque
stringData:
    #ENC[AES256_GCM,data:MEyqe0IbdSdSkInXmpXhqEpazjb3JHJgfTpZaGNYlwD5Sy/VVGUnP8LLK6C52tTUUnJWuZrsqG21dNi0baa7dr9zxuhK7IvaTSpp4yij,iv:mA96vunE1Qpo16nJBtMiOGSBcXyWOR16FtRMNjacQUE=,tag:buyY0kym1lnWuhLlQULbNA==,type:comment]
    #ENC[AES256_GCM,data:Yo/8ymImpX7X+z5TS6DwHYytczEO1Ay7x98c3/gQNbEv8ftulxJFsnZzeh1WPXtl9vMDSJLsF5EjFKABzGaRM0eKaM2T1szS,iv:9yRjv22NimPZv3ddUUfdTmhB0BqRgW3GSEbJ7F2Yc8g=,tag:eI4HwpB/iJrb+smmJa5MdA==,type:comment]
    admin-password: ENC[AES256_GCM,data:XXf0dd081oRNCBlBTtJEg0YiPc5Ih4YoXjVOx3USXv8=,iv:0mA9FSQlfjIK2iSZQxMcFKtwfpLMEL+eitCUbpylRWI=,tag:S08iGRxQsPG/I15XHMOXqA==,type:str]
    join-password: ENC[AES256_GCM,data:hmwlHw4=,iv:lg84oljroFIz3VCAxlzCJI6iifohhx7QJaizlqasqd8=,tag:a/PsRN8gs4L6ppkZu1rnYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ul782d9yhczht238qh9unx5swcjjdy8va7gdhcmgd3duvt5dxfgsa35mjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOa3dqL2dSV0dVdUIzZUlr
            QVhsd3Z0cUJqRkZKa1ArVlNuWG9GVE4xemdvCmIwNmpTMnNoQ2hnaDlCLzM0SHlV
            S0o3d0ljZTBsMjBxT2tHcnZ6eWcwNnMKLS0tIDVHYXZLSFZIZ2lQZytSN0hBUXRX
            QlpoUThtdmpUMUxkNlc3dmpCbDl1clkKWsHcjma5RIFkIRxBej7Mh7qiszXrj3iJ
            MrsRRMvjlwHaaBykW4t6hpZJzb+ftsLKd8twWgrA3UsxAGf6qHrJlA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cy90dzmcmw09wluc6ghvfltf8x2kxcd2pc0uxk6w55m62uwntunsc89jmk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdGZGb0pZSkxMbkpXNzdY
            ZFN1dEJab25vVlZkYkgvYkJhbmF1bGI1YkRRCjh3S1dWbHpDMG9lbkJkSy9DdE8w
            dEVTQjRJK2VFMG1TTFFkK3BXVXg3Z0kKLS0tIHR2ZGd1Rkk2c2R5YWxONVNXWGQy
            QVAzcEYyc3JGczRHQWIxYkVPZWJGRkUKc0TecsmSBid4CUK8dtZS/v/OnzAljNpR
            Qck5PFxIIqbJIWieRGIUV5bGqTVLrGfgC6jOUXHICRg4b4PzrGtPxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T19:45:27Z"
    mac: ENC[AES256_GCM,data:6z//4gPPD5t6Z5Rxtsn37R6y4iKhskCpESh4aT+kCHPprzHMUWaDHH1/9DsgE2bG6v6noQCbrx1VKdGO6LJ3ku/xlB6vtpi35X7SASIaeimk03xXJw7iUCqNtX9VyWpG6/JAP+LqLiJcJM5eXHiwc41OPmnxBRAy5aT7TqBP/EM=,iv:tjYDNiNa+YPOv5xGmZ6X1YtzrezisYrLomN4Kk0JCNE=,tag:QnuVbCQBCXh8zpUkkni+aQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.0
