# Credentials for a Harbor robot account with pull access to the project-zomboid
# project. `auth` is base64("<robot-name>:<robot-secret>"). The registry host has to be
# the literal Harbor hostname -- this file is decrypted at apply time and the host is
# matched against the image reference in hr.yaml.
apiVersion: v1
kind: Secret
metadata:
  name: project-zomboid-pull-credentials
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:UOBxSJzvx5dGscQvQ3jzQHwRuWyt1TfkshIQ4fxCsMhKQqyuST+kqzu1LOOs4jPyxqJq0DNQhFootU8h4oVyLbMpogQ6Vt4M/cFTTzS5KpWPyDV27O4BN9DC4MlvNB1p1SYUj+O/oKxU0fcXGnn1wr+eT4iHXOfR9bpU/S2f/khhY8s4WiUPaCh3emnxPRwje1Jxs/egClm9hKiL8kH4Y3NllVSEiYsidHPBm5hiHd1/dR4=,iv:7MESY6eWlvlgwf4RqzHl6FPL+0zFKvkxvgyPPY9ZOOQ=,tag:cGsWoEaqGhZ12Gyfj0BV+A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ul782d9yhczht238qh9unx5swcjjdy8va7gdhcmgd3duvt5dxfgsa35mjh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMelF0NWkxUXc1N3R6K2VZ
        aU5LUjFib1FBL0MrRVdoQVoxWC8xVTF6WkVFCkpYVTlwaUV1YUNIanV1MWVZUHc2
        dlk4VWhWVjV5S3ZzRWVndSt5SGVnN1EKLS0tIGhLNjVkanVmdnUwSjlLOXpMZUlX
        ZFRVRy82S0YrZkNDeEdRbko0d0FJN2MKru4iar5L/9ayYwnBssukOV3p4CL7FXbJ
        q87YJK0zkgjE9FxCf5hs80nnVKQBk5NPGBX+B9fM3FDBV4J88kHx3Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1cy90dzmcmw09wluc6ghvfltf8x2kxcd2pc0uxk6w55m62uwntunsc89jmk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaWs5azFsenVzVVVRS09p
        cytUUUdOS0lBZkY1RE42STIrdi9TanhIWkZnCkZScTNweWszOUlodDI3ck9BRWE1
        UEdRdVpOWDB5Z1puU1VqZ2JDSGhtV0kKLS0tIG1hSnNDWCtLck1OWUJzL2wvZVhs
        eDBraWZJdHMrT0orajlraDVabUI3TDQK6eVo753bHlNINVQJjrXi/iLIy/SfgUvm
        nuyFEmFd1rfk8zPVQ04JnyTMv2tw9mb8i4PJYO+duIJPs4PwFEM9Mg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-19T19:36:02Z"
  mac: ENC[AES256_GCM,data:ALlw3WtbEH5NfuaKlhQ4EYfxuVzR4BC/EWigAgEyL88Zk8K6UY+vnp7QSAuqkWTD+9Wg7KM2W9ot0YcKmC4GjWRbK2ygYVtIZ/jIv/fxf5y7vY9V4CsQwtMzN4nBwfVsha4Jhqj3DKccZgqnrocbpBRnfeleZzcmZbn6F/3s2TM=,iv:7oVNnUyVNAJ5OW4NeGRMUx0In9EZlZo7C3IBEXs1JtA=,tag:PQBKZ0SRggs4vKTVl7pw5g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.0
