#!/usr/bin/bash
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

kexec -l --reuse-cmdline --initrd=/boot/pve/initrd.img /boot/pve/vmlinuz
sync
umount -a
kexec -e
