---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: seerr-envoy-pg-config
    files:
      - envoy.yaml=./postgres.yaml
      - postgres-client-cert-sds.yaml=./postgres-client-cert-sds.yaml
      - postgres-validation-context-sds.yaml=./postgres-validation-context-sds.yaml
    options:
      labels:
        kyverno.home.arpa/reload: "true"
      disableNameSuffixHash: true
