---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/resources.teleport.dev/teleportbotv1_v1.json
apiVersion: resources.teleport.dev/v1
kind: TeleportBotV1
metadata:
  name: tape-archiver-data-worker
spec:
  roles:
    - tape-archiver-data-worker-bot
