---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  # Unfortunately because this needs to be mounted in the server pods, it
  # cannot live in the "configuration" fluxtomization
  - name: authentik-css
    files:
      - custom.css
    options:
      labels:
        # subPath mounts never see ConfigMap updates, so restart instead
        kyverno.home.arpa/reload: "true"
      disableNameSuffixHash: true
