apiVersion: v1
kind: Secret
metadata:
    name: insurgency-server-discord-webhook
type: Opaque
stringData:
    webhookUrl: ENC[AES256_GCM,data:CBXM4XDaysSdk61L92+r4jStiHGSAPFi95ms6v1UuZM9hXxInMmYcU1Tz91GxeoXyvg2b4gxzor1dqVPKIbN1dm4+zA09VGM8A/ChgmPQXfFpcA3UVAiWeiYabEXC8g/qCJYaUb0OKyiDgvLfWs8aWRxhgdgQh81bA==,iv:1xTSmyK3k2HeP9xNaZ3RLOW4MHADPPGW63zUFZsW7gg=,tag:kSzAZcVJffxngsNLMFVz3g==,type:str]
    testWebhookUrl: ENC[AES256_GCM,data:TB4CGOloLC1NBm0KNH+lOcOZ4DMxIJwKX0WQC9hhQl1XS0haKsZkB0qpEWCBAk4fq5VFGB/wjOykHW39brsK9KD3S7HhqrcT94HgITcM1GnLFFPDmh1eMZgsTzeU1vxIta8mHMqLVtedKwpRhNapiCdNK/YPDqRHYg==,iv:U8wlQFdA2gzGxJy2bhiNPpEettTaCAjr0QwzCUWHHWM=,tag:br0zmaqGxTtZ1GM/k5ZAIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ul782d9yhczht238qh9unx5swcjjdy8va7gdhcmgd3duvt5dxfgsa35mjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRS9ic0tVZUNLWHhPNmhj
            ak5FbzdjS2J5NWJQc3RWZ3ZiSW4zTVJub2pJCnVER0llbG9ZWHJaekUwTCtCdTFW
            QWU2MXZWR2F3TEVMdmdUcUljalpuYk0KLS0tIEdNNkNQU2VJcThodUZaVVFxZXdB
            WXlTbWsrMlRGRGRHeklBR1lSblMvZ1kKMzK5QPZd76oco10ks6UomYh/U0ipAldd
            DhS0Wfy9Ld1XeHchZqCAP6UkoClpJq+zzRJMAUoHMmgKcRVuRLINqg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cy90dzmcmw09wluc6ghvfltf8x2kxcd2pc0uxk6w55m62uwntunsc89jmk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NitUeWw3NE84WDIrOWw1
            WE5sR0ViZTRFdUR3UXNVT2o1cDJueGZIVkJzCkkvV2hvQUVmMXo5cmMyQzh4S1cr
            S1dyWUhWeWZkbUx4QXlnNCtlNTArNlEKLS0tIHp2VTNtbnZ1VEo2cEt0c29wVkh5
            Ni9tbng2cWJ3WHBsRWFBdGxucE9TMjgK9JsZkrdhA4edogYoD+7gYcy4JCLGpzKm
            BGjaSHmy9ctBmBHz9KzSVlGSakN9c+7zkWoQCrO4ZRrXCAgzrRlDOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-06T08:18:30Z"
    mac: ENC[AES256_GCM,data:RRCyntxMcH4l4EqjAvjE/QBdQyCfO6iZ39ZwTrTpObWYBTCNZ6OB73vSxdBRP4aCncUxkx9m51izs369zBzsS0zD0Misd+BBGNfmkp4gIR4KrNOePBMGASfr4NXEYEFjc382Ma6T+es4y+ON3TCzLDRPfI076cyfM3YW1Zl+YRw=,iv:hi4ag3DpUtuhPH4oCXVom70S/bxN0TmPU8PouqUcblQ=,tag:vZNz5N4RQPyXzr0/uDvFww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.0
